# Generated by Django 4.0 on 2022-02-03 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='regevents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=255)),
                ('eventname', models.CharField(max_length=255)),
                ('link', models.URLField(max_length=100)),
                ('lastdate', models.DateField()),
                ('eventdate', models.DateField()),
                ('time', models.TimeField()),
                ('location', models.CharField(max_length=100)),
                ('slots', models.CharField(max_length=100)),
            ],
        ),
    ]
