# Generated by Django 4.0 on 2022-02-04 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nonclubmembers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regevents',
            name='lastdate',
        ),
        migrations.RemoveField(
            model_name='regevents',
            name='slots',
        ),
    ]
