# Generated by Django 4.0 on 2022-02-04 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubmembers', '0002_events_image_alter_events_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='image',
        ),
    ]
