# Generated by Django 4.0 on 2022-02-04 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubmembers', '0003_remove_events_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='poster',
            field=models.ImageField(default=True, upload_to='veventz/images/'),
        ),
    ]
