# Generated by Django 4.0 on 2022-02-04 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubmembers', '0006_alter_events_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='poster',
            field=models.ImageField(upload_to='clubmembers/images/'),
        ),
    ]
